# Generated by Django 3.2.3 on 2021-05-18 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('place', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('placeInformation', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=5)),
                ('caution', models.TextField(default='')),
                ('pub_date', models.DateTimeField(default='')),
                ('no', models.IntegerField(default=0)),
                ('yes', models.IntegerField(default=0)),
                ('pet', models.BooleanField()),
                ('tripType', models.CharField(max_length=10)),
                ('place', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cautionboard.text')),
            ],
        ),
    ]
