# Generated by Django 3.2.2 on 2021-05-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('author', models.CharField(max_length=5)),
                ('place', models.CharField(max_length=10)),
                ('caution', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField()),
                ('no', models.IntegerField()),
                ('yes', models.IntegerField()),
                ('pet', models.BooleanField()),
                ('tripType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=10)),
                ('plaInt', models.TextField()),
            ],
        ),
    ]
